SYSTEM:
  NUM_GPUS: 1
  NUM_CPUS: 4
SOLVER:
  NAME: Adam
  LR_SCHEDULER_NAME: WarmupCosineLR
  BASE_LR: 0.0001
  ITERATION_STEP: 1
  ITERATION_SAVE: 10000
  ITERATION_TOTAL: 100000
  ITERATION_VAL: 10000
  SAMPLES_PER_BATCH: 2
MODEL:
  # ARCHITECTURE: 'prior_enhanced_unet_3d'
  ARCHITECTURE: 'unet_3d'
  BLOCK_TYPE: 'residual'
  FILTERS: [32, 64, 96, 128, 160]
  BLOCKS: [2, 2, 2, 2]    # only useful for FPN
  INPUT_SIZE: [4, 512, 512]
  OUTPUT_SIZE: [4, 512, 512]
DATASET:
  OUTPUT_PATH: outputs/AC3-AC4/res_unet
INFERENCE:
  OUTPUT_PATH: outputs/AC3-AC4/res_unet/test
  INPUT_SIZE: [4, 512, 512]
  OUTPUT_SIZE: [4, 512, 512]
  STRIDE: [2, 256, 256]
 